name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.0.1
homepage: https://github.com/anicdh
author: andoan <anic.dh@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bip39: ^1.0.3
  bip32: ^1.0.5
  pointycastle: ^1.0.2
  hex: ^0.1.2
  bs58check: ^1.0.1
  meta: ^1.2.2
  bech32: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
